name: Build Docker Image

on:
  workflow_call:
    inputs:
      dockerhub-username:
        required: true
        type: string
      dockerhub-token:
        required: true
        type: string

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the current release version
        id: get_version
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ inputs.dockerhub-token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gfrancv/vilbot:latest, gfrancv/vilbot:${{ env.RELEASE_VERSION }}
