name: Release

on:
  release:
    types: [created]

jobs:
  build_docker_image:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
